import type {
  AxiosInstance,
  AxiosInterceptorManager,
  AxiosRequestConfig,
  AxiosRequestHeaders,
  AxiosResponse,
  InternalAxiosRequestConfig
} from 'axios';
import type { CacheInstance, CacheProperties } from './cache.ts';

/**
 * A response that is slightly different from the original Axios response, containing
 * information about the cache and other required properties.
 *
 * @template R The type returned by this response
 * @template D The type that the request body was
 * @see https://axios-cache-interceptor.js.org/config/response-object
 */
// biome-ignore lint/complexity/noBannedTypes: AxiosResponse uses {} as its default header type.
export interface CacheAxiosResponse<R = any, D = any, P = any> extends AxiosResponse<R, D, {}, P> {
  config: InternalCacheRequestConfig<R, D, P>;

  /**
   * The [Request ID](https://axios-cache-interceptor.js.org/guide/request-id) used in
   * this request.
   *
   * It may have been generated by the [Key
   * Generator](https://axios-cache-interceptor.js.org/guide/request-id#custom-generator)
   * or a custom one provided by
   * [`config.id`](https://axios-cache-interceptor.js.org/config/request-specifics#id)
   *
   * @see https://axios-cache-interceptor.js.org/config/response-object#id
   */
  id: string;

  /**
   * A simple boolean indicating if the request returned data from the cache or from the
   * network call.
   *
   * This does not indicate if the request was capable of being cached or not, as options
   * like
   * [`cache.override`](https://axios-cache-interceptor.js.org/config/request-specifics#cache-override)
   * may have been enabled.
   *
   * @see https://axios-cache-interceptor.js.org/config/response-object#cached
   */
  cached: boolean;

  /**
   * A simple boolean indicating whether the data returned by the request is from a valid
   * or stale cache.
   *
   * @see https://axios-cache-interceptor.js.org/config/response-object#stale
   */
  stale?: boolean;
}

/**
 * Options that can be overridden per request
 *
 * @template R The type returned by this response
 * @template D The type for the request body
 */
export interface CacheRequestConfig<R = any, D = any, P = any> extends AxiosRequestConfig<D, P> {
  /**
   * The [Request ID](https://axios-cache-interceptor.js.org/guide/request-id) used in
   * this request.
   *
   * It may have been generated by the [Key
   * Generator](https://axios-cache-interceptor.js.org/guide/request-id#custom-generator)
   * or a custom one provided by
   * [`config.id`](https://axios-cache-interceptor.js.org/config/request-specifics#id)
   *
   * @default 'auto generated by the current key generator'
   * @see https://axios-cache-interceptor.js.org/config/response-object#id
   */
  id?: string;

  /**
   * The cache option available through the request config is where all the cache
   * customization happens.
   *
   * You can pass an object with cache properties to customize cache behavior.
   *
   * **Note:** Setting `cache: false` is still supported for backward compatibility, but
   * will be removed in the next major release. Use `cache: { enabled: false }` instead.
   *
   * This does not mean that the current cache will be excluded from the storage.
   *
   * @default 'inherits from global configuration'
   * @see https://axios-cache-interceptor.js.org/config/response-object#cache
   */
  cache?: Partial<CacheProperties<R, D>> | false;
}

/**
 * Cached version of type {@link InternalAxiosRequestConfig}
 *
 * @deprecated This interface will be hidden in future versions. Please tell us why you need it at https://github.com/arthurfiorette/axios-cache-interceptor/issues/1158
 */
export interface InternalCacheRequestConfig<R = any, D = any, P = any>
  extends CacheRequestConfig<R, D, P> {
  headers: AxiosRequestHeaders;
}

/**
 * Same as the AxiosInstance but with CacheRequestConfig as a config type and
 * CacheAxiosResponse as response type.
 *
 * @see https://axios-cache-interceptor.js.org/guide/getting-started
 */
export interface AxiosCacheInstance extends CacheInstance, AxiosInstance {
  /**
   * @template T1 The type returned by this response
   * @template R1 The custom response type that the request can return
   * @template D1 The type that the request body uses
   */
  <T1 = any, D1 = any, R1 = CacheAxiosResponse<T1, D1>, P1 = any>(
    config: CacheRequestConfig<T1, D1, P1>
  ): Promise<R1>;
  /**
   * @template T2 The type returned by this response
   * @template R2 The custom response type that the request can return
   * @template D2 The type that the request body uses
   */
  <T2 = any, D2 = any, R2 = CacheAxiosResponse<T2, D2>, P2 = any>(
    url: string,
    config?: CacheRequestConfig<T2, D2, P2>
  ): Promise<R2>;

  defaults: AxiosInstance['defaults'] & {
    cache: CacheProperties;
  };

  interceptors: {
    request: AxiosInterceptorManager<InternalCacheRequestConfig<unknown, unknown>>;
    response: AxiosInterceptorManager<
      Partial<CacheAxiosResponse<unknown, unknown>> & AxiosResponse<unknown, unknown>
    >;
  };

  /** @template D The type that the request body uses */
  getUri<D, P>(config?: CacheRequestConfig<any, D, P>): string;

  /**
   * @template T The type returned by this response
   * @template R The custom response type that the request can return
   * @template D The type that the request body uses
   */
  request<T = any, D = any, R = CacheAxiosResponse<T, D>, P = any>(
    config?: CacheRequestConfig<T, D, P>
  ): Promise<R>;

  /**
   * @template T The type returned by this response
   * @template R The custom response type that the request can return
   * @template D The type that the request body uses
   */
  get<T = any, D = any, R = CacheAxiosResponse<T, D>, P = any>(
    url: string,
    config?: CacheRequestConfig<T, D, P>
  ): Promise<R>;

  /**
   * @template T The type returned by this response
   * @template R The custom response type that the request can return
   * @template D The type that the request body uses
   */
  delete<T = any, D = any, R = CacheAxiosResponse<T, D>, P = any>(
    url: string,
    config?: CacheRequestConfig<T, D, P>
  ): Promise<R>;

  /**
   * @template T The type returned by this response
   * @template R The custom response type that the request can return
   * @template D The type that the request body uses
   */
  head<T = any, D = any, R = CacheAxiosResponse<T, D>, P = any>(
    url: string,
    config?: CacheRequestConfig<T, D, P>
  ): Promise<R>;

  /**
   * @template T The type returned by this response
   * @template R The custom response type that the request can return
   * @template D The type that the request body uses
   */
  options<T = any, D = any, R = CacheAxiosResponse<T, D>, P = any>(
    url: string,
    config?: CacheRequestConfig<T, D, P>
  ): Promise<R>;

  /**
   * @template T The type returned by this response
   * @template R The custom response type that the request can return
   * @template D The type that the request body uses
   */
  post<T = any, D = any, R = CacheAxiosResponse<T, D>, P = any>(
    url: string,
    data?: D,
    config?: CacheRequestConfig<T, D, P>
  ): Promise<R>;

  /**
   * @template T The type returned by this response
   * @template R The custom response type that the request can return
   * @template D The type that the request body uses
   */
  postForm<T = any, D = any, R = CacheAxiosResponse<T, D>, P = any>(
    url: string,
    data?: D,
    config?: CacheRequestConfig<T, D, P>
  ): Promise<R>;

  /**
   * @template T The type returned by this response
   * @template R The custom response type that the request can return
   * @template D The type that the request body uses
   */
  put<T = any, D = any, R = CacheAxiosResponse<T, D>, P = any>(
    url: string,
    data?: D,
    config?: CacheRequestConfig<T, D, P>
  ): Promise<R>;

  /**
   * @template T The type returned by this response
   * @template R The custom response type that the request can return
   * @template D The type that the request body uses
   */
  putForm<T = any, D = any, R = CacheAxiosResponse<T, D>, P = any>(
    url: string,
    data?: D,
    config?: CacheRequestConfig<T, D, P>
  ): Promise<R>;

  /**
   * @template T The type returned by this response
   * @template R The custom response type that the request can return
   * @template D The type that the request body uses
   */
  patch<T = any, D = any, R = CacheAxiosResponse<T, D>, P = any>(
    url: string,
    data?: D,
    config?: CacheRequestConfig<T, D, P>
  ): Promise<R>;

  /**
   * @template T The type returned by this response
   * @template R The custom response type that the request can return
   * @template D The type that the request body uses
   */
  patchForm<T = any, D = any, R = CacheAxiosResponse<T, D>, P = any>(
    url: string,
    data?: D,
    config?: CacheRequestConfig<T, D, P>
  ): Promise<R>;
}
