name: Code CI

on:
  push:

jobs:
  build:
    name: Build and test code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup node and restore cached dependencies
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install packages
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --ci --coverage

      - name: Build
        run: yarn build

      - name: ESCheck
        run: yarn check

      - name: Publish to Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
